default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: splurty_development

test:
  <<: *default
  database: splurty_test

production:
  <<: *default
  database: splurty_production
  # username: splurty
<<<<<<< HEAD
  # password: <%= ENV['SPLURTY_DATABASE_PASSWORD'] %>
=======
  # password: <%= ENV['SPLURTY_DATABASE_PASSWORD'] %>
>>>>>>> 5d8c51d285b9a1c360834e92cd7e1bfa67ce9737
